### ISSUE TITLE
Expose configuration parameters as ENV variables

### ISSUE THREAD

**Issue by dbonino** [noiapp/noiapp-backend-old#29]
To ease Docker-based distribution of the backend it would be better to amend the application.properties file to include environment variables (plus default, id needed) thus easing the deployment of the backend inside a Docker container. It is prettyi easy, for example, for a sample server_address parameter it would require to use the following form:

``server.address=${BACKEND_ADDRESS:0.0.0.0}``

where ``BACKEND_ADDRESS`` is the exposed environment variable

**Comment by slyfer** [comment]
Spring boot already have this feature: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config

**Comment by dbonino** [comment]
Exactly what I was saying....
